In [1]:
import numpy as np


In [15]:
import numpy as np
import matplotlib.pyplot as plt
from skimage import data, filters, color, morphology
from skimage.segmentation import flood, flood_fill
import scipy.ndimage as ndi

In [55]:
test = np.zeros((6, 6, 6))
test[1:5, 1:5, 1:5] = 2
test[2:4, 2:4, 2:4] = 0
test

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 2., 2., 2., 2., 0.],
        [0., 2., 2., 2., 2., 0.],
        [0., 2., 2., 2., 2., 0.],
        [0., 2., 2., 2., 2., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 2., 2., 2., 2., 0.],
        [0., 2., 0., 0., 2., 0.],
        [0., 2., 0., 0., 2., 0.],
        [0., 2., 2., 2., 2., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 2., 2., 2., 2., 0.],
        [0., 2., 0., 0., 2., 0.],
        [0., 2., 0., 0., 2., 0.],
        [0., 2., 2., 2., 2., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 2., 2., 2., 2., 0.],
        [0., 2., 2., 2., 2., 0.],
        [0., 2., 2., 2., 2., 0.],
        [0., 2., 2., 2., 2., 0.],
      

In [56]:
mask = flood(test, (2, 2, 2))
image_flooded = test.copy()
image_flooded[mask] = 2
image_flooded

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 2., 2., 2., 2., 0.],
        [0., 2., 2., 2., 2., 0.],
        [0., 2., 2., 2., 2., 0.],
        [0., 2., 2., 2., 2., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 2., 2., 2., 2., 0.],
        [0., 2., 2., 2., 2., 0.],
        [0., 2., 2., 2., 2., 0.],
        [0., 2., 2., 2., 2., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 2., 2., 2., 2., 0.],
        [0., 2., 2., 2., 2., 0.],
        [0., 2., 2., 2., 2., 0.],
        [0., 2., 2., 2., 2., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 2., 2., 2., 2., 0.],
        [0., 2., 2., 2., 2., 0.],
        [0., 2., 2., 2., 2., 0.],
        [0., 2., 2., 2., 2., 0.],
      

In [47]:
retour = ndi.binary_fill_holes(test).astype(int)

In [39]:
retour = retour * -3

In [48]:
retour.astype(int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 1, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 1, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 1, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [31]:
test2 = np.arange(1,101).reshape(10,10)

In [42]:
test2[retour.astype(bool)] = 0
test2

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,   0,   0,   0,   0,  49,  50],
       [ 51,  52,  53,  54,   0,   0,   0,   0,  59,  60],
       [ 61,  62,  63,  64,   0,   0,   0,   0,  69,  70],
       [ 71,  72,  73,  74,   0,   0,   0,   0,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [ ]:
radius =3.139076411875725 -- X.shape = (29,)
radius =6.139076411875725 -- X.shape = (121,)

In [57]:
(3.14**2) * 3.14

30.959144000000002

In [61]:
(6.139076411875725**2) * np.pi

118.40115820055898

In [38]:
from skimage import filters, morphology, data as skidata, exposure, draw

def mkfiber(dims_size, length, radius, azth, lat, offset_xyz):
    """Computes fiber coordinates and its length.
    Computes a fiber of speficied `length`, `radius`, oriented under azimuth `azth` and
    latitude / elevation `lat` angles shifted to `offset_xyz` from the center of a volume of
    size `dims_size`.
    Parameters
    ----------
    dims_size : tuple
        Indicates the size of the volume.
    length : integer
        Indicates the length of the simulated fiber.
    radius : integer
        Indicates the radius of the simulated fiber.
    azth : float
        Indicates the azimuth component of the orientation angles of the fiber in radians.
    lat : float
        Indicates the latitude / elevation component of the orientation angles of the fiber
        in radians.
    offset_xyz : tuple
        Indicates the offset from the center of the volume where the fiber will be generated.
    Returns
    -------
    fiber_pts, fiber_len : tuple of array and number
        The array of fiber coordinates and the length.
    """
    dims_size = np.array(dims_size)

    half_pi = np.pi / 2.
    mx = np.array([[1., 0., 0],
                   [0., np.cos(lat), np.sin(lat)],
                   [0., -np.sin(lat), np.cos(lat)]])
    azth += half_pi
    mz = np.array([[np.cos(azth), -np.sin(azth), 0],
                   [np.sin(azth), np.cos(azth), 0],
                   [0., 0., 1.]])

    # Directional vector
    dl = 1
    dir_vec = np.array([0, 0, 1])
    dir_vec = np.dot(mx, dir_vec)
    dir_vec = np.dot(mz, dir_vec)
    dx, dy, dz = dir_vec[0], dir_vec[1], dir_vec[2]

    # Compute length
    n_steps = np.round(length / dl)
    half_steps = int(np.ceil(n_steps / 2.))
    steps = range(half_steps - int(n_steps), half_steps)

    # Draw circle perpedicular to the directional vector
    X, Y = draw.circle(0, 0, radius)
    Z = np.repeat(0, len(Y))
    circle_pts = np.array([X, Y, Z])
    circle_pts = np.dot(mx, circle_pts)
    circle_pts = np.dot(mz, circle_pts)

    # Propogate the circle profile along the directional vector
    #return circle_pts
    #slice_pts = np.array(zip(*circle_pts))
    slice_pts = circle_pts.T
    dxyz = np.array([dx, dy, dz])
    step_shifts = np.array([step * dxyz for step in steps])  # [(dx,dy,dz), ...] for each step
    center_shift = dims_size * 0.5 + offset_xyz  # (x, y ,z)
    
    print("step_shifts[0] = ", step_shifts[0])
    print("step_shifts[0].shape = ", step_shifts[0].shape)
    slices_pts = np.round(np.array([slice_pts + step_shift + center_shift
                                    for step_shift in step_shifts]))

    # Filter all the points which are outside the boundary
    pt_filter = lambda pt: np.all(np.greater_equal(pt, (0, 0, 0))) and \
                            np.all(np.less(np.array(pt), dims_size))
    n_slices = 0
    fiber_pts = None
    for pts in slices_pts:
        slice_pts_mask = [pt_filter(pt) for pt in pts]
        slice_pts = pts[slice_pts_mask].astype(np.int32)
        if len(slice_pts) > 0:
            n_slices += 1
            fiber_pts = slice_pts if fiber_pts is None else \
                        np.concatenate((fiber_pts, slice_pts))
    # number of slices, e.g. steps.
    fiber_len = np.round(n_slices * dl).astype(np.int32)
    fiber_pts = fiber_pts.astype(np.int32)
    return fiber_pts, fiber_len


In [39]:
dims_size=[128, 128, 128]
length=58
radius=2.353286956138798
azth=2.133338855915478
lat=0.1707760504979278
offset_xyz=[-13, -29, -28]
ret = mkfiber(dims_size, length, radius, azth, lat, offset_xyz)

step_shifts[0] =  [ -2.6285423    4.16899977 -28.57814211]
step_shifts[0].shape =  (3,)


/home/md4/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:52: FutureWarning: `draw.circle` is deprecated in favor of `draw.disk`.`draw.circle` will be removed in version 0.19


In [11]:
test1 = np.array([[0, 0, 0], [1, 0, 1], [2, -1, 0], [1, 2, 3], [1, 3, -2]])
test2 = np.array([[0, 0, 0], [1, 0, 1], [2, 1, 0], [1, 2, 3], [1, 3, 2]])

test2.shape

(5, 3)

In [ ]:
from scipy.ndimage import filters

In [2]:
def structure_tensor_3d(volume, sigma, rho, out=None):
    """Structure tensor for 3D image data.
    Arguments:
        volume: array_like
            A 3D array. Pass ndarray to avoid copying volume.
        sigma: scalar
            A noise scale, structures smaller than sigma will be removed by smoothing.
        rho: scalar
            An integration scale giving the size over the neighborhood in which the
            orientation is to be analysed.
        out: ndarray, optional
            A Numpy array with the shape (6, volume.shape) in which to place the output.
    Returns:
        S: ndarray
            An array with shape (6, volume.shape) containing elements of structure tensor
            (s_xx, s_yy, s_zz, s_xy, s_xz, s_yz).
    Authors: vand@dtu.dk, 2019; niejep@dtu.dk, 2019-2020
    """

    # Make sure it's a Numpy array.
    volume = np.asarray(volume)

    # Computing derivatives (scipy implementation truncates filter at 4 sigma).
    Vx = filters.gaussian_filter(volume, sigma, order=[0, 0, 1], mode='nearest')
    Vy = filters.gaussian_filter(volume, sigma, order=[0, 1, 0], mode='nearest')
    Vz = filters.gaussian_filter(volume, sigma, order=[1, 0, 0], mode='nearest')

    if out is None:
        # Allocate S.
        S = np.empty((6, ) + volume.shape, dtype=volume.dtype)
    else:
        # S is already allocated. We assume the size is correct.
        S = out

    # Integrating elements of structure tensor (scipy uses sequence of 1D).
    tmp = np.empty(volume.shape, dtype=volume.dtype)
    np.multiply(Vx, Vx, out=tmp)
    filters.gaussian_filter(tmp, rho, mode='nearest', output=S[0])
    np.multiply(Vy, Vy, out=tmp)
    filters.gaussian_filter(tmp, rho, mode='nearest', output=S[1])
    np.multiply(Vz, Vz, out=tmp)
    filters.gaussian_filter(tmp, rho, mode='nearest', output=S[2])
    np.multiply(Vx, Vy, out=tmp)
    filters.gaussian_filter(tmp, rho, mode='nearest', output=S[3])
    np.multiply(Vx, Vz, out=tmp)
    filters.gaussian_filter(tmp, rho, mode='nearest', output=S[4])
    np.multiply(Vy, Vz, out=tmp)
    filters.gaussian_filter(tmp, rho, mode='nearest', output=S[5])

    return S

In [3]:
volume = np.random.random((128,128,128))

In [4]:
sigma = 1.5
rho = 5.5
S = structure_tensor_3d(volume, sigma, rho)

In [5]:
import structure_tensor

In [6]:
import numpy as np
from scipy import ndimage as ndi
from skimage import morphology
from quanfima import simulation
from quanfima import morphology as mrph
from quanfima import qf_utils
from quanfima import visualization as vis

In [7]:
volume, lat_ref, azth_ref, diameter, _, _ = \
          simulation.simulate_fibers((128,128,128), n_fibers=30, max_fails=100,
                                     radius_lim=(2, 3), gap_lim=(3,5))
volume = volume.astype(np.uint8)
volume = ndi.binary_fill_holes(volume)
volume = ndi.median_filter(volume, footprint=morphology.ball(2))
lat_ref = ndi.median_filter(lat_ref, footprint=morphology.ball(2))
azth_ref = ndi.median_filter(azth_ref, footprint=morphology.ball(2))

# prepare data and analyze fibers
pdata, pskel, pskel_thick = utils.prepare_data(volume)
oprops =  mrph.estimate_tensor_parallel('dataset_orientation_w36',
                                        pskel, pskel_thick, 36,
                                        '../../data/results')

odata = np.load(oprops['output_path']).item()
lat, azth, skel = odata['lat'], odata['azth'], odata['skeleton']

dprops = mrph.estimate_diameter_single_run('dataset_diameter',
                                           '../../data/results',
                                           pdata, skel, lat, azth)
dmtr = np.load(dprops['output_path']).item()['diameter']

# plot results
vis.plot_3d_orientation_map('dataset_w36', lat, azth,
                            output_dir='../../data/results',
                            camera_azth=40.47,
                            camera_elev=32.5,
                            camera_fov=35.0,
                            camera_loc=(40.85, 46.32, 28.85),
                            camera_zoom=0.005124)

vis.plot_3d_diameter_map('dataset_w36', dmtr,
                         output_dir='../../data/results',
                         measure_quantity='vox',
                         camera_azth=40.47,
                         camera_elev=32.5,
                         camera_fov=35.0,
                         camera_loc=(40.85, 46.32, 28.85),
                         camera_zoom=0.005124,
                         cb_x_offset=5,
                         width=620)

type(circle_pts):  <class 'numpy.ndarray'>  -- circle_pts (3, 21)
type(slice_pts):  <class 'numpy.ndarray'>  -- slice_pts ()
type(step_shifts):  <class 'numpy.ndarray'>  -- (74, 3)
type(center_shift):  <class 'numpy.ndarray'>  -- (3,)


/home/md4/Documents/projets_personnels/quanfima/quanfima/simulation.py:78: FutureWarning: `draw.circle` is deprecated in favor of `draw.disk`.`draw.circle` will be removed in version 0.19
  X, Y = draw.circle(0, 0, radius)


TypeError: unsupported operand type(s) for +: 'zip' and 'float'

In [41]:
test = []

In [43]:
test is None

False